# Generated by Django 5.2 on 2025-04-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_user_avatar_useractivity'),
        ('movies', '0003_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_tags',
            field=models.ManyToManyField(blank=True, to='movies.tag'),
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
