# Generated by Django 5.2 on 2025-05-05 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_user_favorite_movies_user_preferred_tags_and_more'),
        ('movies', '0006_alter_director_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Изображение профиля', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Когда создана запись'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Когда зарегистрировался'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Необязательно, но должно быть уникальным', max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, help_text='Фильмы, добавленные в избранное', related_name='favorited_by', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли пользователь (не удален)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Может ли заходить в админку'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_tags',
            field=models.ManyToManyField(blank=True, help_text='Предпочитаемые жанры/теги', to='movies.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('user', 'Пользователь')], default='user', help_text='Определяет уровень доступа', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, help_text='Уникальное имя для входа в систему', max_length=255, unique=True, verbose_name='Логин'),
        ),
    ]
