# Generated by Django 5.2 on 2025-04-23 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя актера')),
            ],
            options={
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актеры',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя режиссера')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('poster_url', models.URLField(blank=True, default='', null=True, verbose_name='Ссылка на постер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('actors', models.ManyToManyField(related_name='movies', to='movies.actor', verbose_name='Актеры')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.director', verbose_name='Режиссер')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_movies', to=settings.AUTH_USER_MODEL, verbose_name='Понравилось пользователям')),
                ('tags', models.ManyToManyField(blank=True, to='movies.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-rating'],
                'indexes': [models.Index(fields=['title'], name='movies_movi_title_652549_idx'), models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'), models.Index(fields=['rating'], name='movies_movi_rating_8fd49a_idx')],
            },
        ),
    ]
