# Generated by Django 5.2 on 2025-05-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_review_options_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_title_652549_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_release_b7ac7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_rating_8fd49a_idx',
        ),
    ]
