# Generated by Django 5.2 on 2025-05-05 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_options_alter_review_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['name'], 'verbose_name': 'Режиссер', 'verbose_name_plural': 'Режиссеры'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-rating', 'title'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Жанр/Тег', 'verbose_name_plural': 'Жанры/Теги'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'Активность пользователя', 'verbose_name_plural': 'Активности пользователей'},
        ),
        migrations.AddField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(default='view', help_text="Например: 'view', 'like', 'review'", max_length=50, verbose_name='Тип активности'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(help_text='Введите полное имя актера', max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(help_text='Введите полное имя режиссера', max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.actor', verbose_name='Актерский состав'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в систему'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, help_text='Полное описание сюжета', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, help_text='Основной режиссер фильма', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.director', verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_movies', to=settings.AUTH_USER_MODEL, verbose_name='В избранном у пользователей'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, default='', help_text='Ссылка на изображение постера', null=True, verbose_name='Постер фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Средняя оценка от 0 до 10', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(help_text='Дата первого показа', verbose_name='Дата премьеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите подходящие жанры', to='movies.tag', verbose_name='Жанры и теги'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Полное официальное название', max_length=255, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Оценка от 1 до 10', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(help_text='Ваше мнение о фильме', verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Максимум 50 символов', max_length=50, unique=True, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='movies.movie', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата активности'),
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['name'], name='movies_acto_name_2656bd_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='movies_movi_title_652549_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='movies_movi_rating_8fd49a_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type'], name='movies_user_user_id_9dbe43_idx'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 10)), name='rating_range'),
        ),
    ]
